version: '3'
services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD=pg_password
  
  redis:
    image: 'redis:alpine'
  
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=pg_password
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
      - redis

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    depends_on:
      - api
    stdin_open: true

  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - '8080:80'
    depends_on:
      - api
      - client
