services:

  rabbitmq:
    image: 'rabbitmq:3.13.3-alpine'
    healthcheck:
      test: nc -z localhost 5672 || exit 1
      interval: 30s
      timeout: 10s
      retries: 4
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit heartbeat 900

  redis:
    image: 'redis:7.2.5-alpine'

  postgres:
    image: 'postgres:16.3-alpine3.20'
    environment:
      - POSTGRES_PASSWORD=pg_password

  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - rabbitmq
    restart: on-failure

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=pg_password
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: on-failure

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    depends_on:
      - api
    stdin_open: true
    restart: on-failure
  
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '8080:80'
    depends_on:
      - api
      - client
