apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: taktzeit
  labels:
    app: web
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
        app: web
        version: 1.0.0
    spec:
      containers:
      - name: client
        image: index.docker.io/edaddario/client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3010
        resources:
          limits:
            memory: 8Mi
            cpu: 250m
          requests:
            memory: 6Mi
            cpu: 10m
