apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip
  namespace: taktzeit
  labels:
    app: web
    version: 1.0.0
spec:
  type: ClusterIP
  selector:
    component: client
  ports:
    - port: 3010
      name: http
      targetPort: 3010
