apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  namespace: taktzeit
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: taktzeit
  labels:
    app: database
    version: 1.0.0
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
