apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              service:
                name: client-cluster-ip
                port:
                  number: 3000
            pathType: Exact
          - path: /api/?(.*)
            backend:
                service:
                  name: api-cluster-ip
                  port:
                    number: 5000
            pathType: Exact
