apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: nginx
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  labels:
    app: ingress
    version: 1.0.0
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: client-cluster-ip
      port:
        number: 80
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              service:
                name: client-cluster-ip
                port:
                  number: 3010
            pathType: Exact
          - path: /api/?(.*)
            backend:
                service:
                  name: api-cluster-ip
                  port:
                    number: 5010
            pathType: Exact
