#!/bin/zsh
echo -e "\n$fg_bold[red]Deploying RabbitMQ$reset_color"
kubectl apply -f rabbitmq-cluster-ip.yml -f rabbitmq-deployment.yml
echo -e "\n$fg_bold[red]Sleeping 30 sec to allow for RabbitMQ startup$reset_color"
sleep 30
echo -e "\n$fg_bold[red]Deploying Redis$reset_color"
kubectl apply -f redis-cluster-ip.yml -f redis-deployment.yml
echo -e "\n$fg_bold[red]Creating Peristent Volume Claim $reset_color"
kubectl apply -f database-pvc.yml
echo -e "\n$fg_bold[red]Deploying Postgres$reset_color"
kubectl apply -f postgres-cluster-ip.yml -f postgres-deployment.yml
echo -e "\n$fg_bold[red]Deploying WORKER component$reset_color"
kubectl apply -f worker-deployment.yml
echo -e "\n$fg_bold[red]Deploying WORKER horizontal pod autoscaler $reset_color"
kubectl apply -f worker-hpa.yml
echo -e "\n$fg_bold[red]Deploying API component$reset_color"
kubectl apply -f api-cluster-ip.yml -f api-deployment.yml
echo -e "\n$fg_bold[red]Deploying CLIENT component$reset_color"
kubectl apply -f client-cluster-ip.yml -f client-deployment.yml
echo -e "\n$fg_bold[red]Deploying ingress service$reset_color"
kubectl apply -f ingress-service.yml
echo -e "\n$fg_bold[red]Finished deploying cloud native system$reset_color\n"
