#!/bin/zsh
autoload colors
colors
echo -e "\n$fg_bold[red]Deleting ingress service$reset_color"
kubectl delete -f ingress-service.yml
echo -e "\n$fg_bold[red]Deleting CLIENT service$reset_color"
kubectl delete -f client-cluster-ip.yml -f client-deployment.yml
echo -e "\n$fg_bold[red]Deleting API service$reset_color"
kubectl delete -f api-cluster-ip.yml -f api-deployment.yml
echo -e "\n$fg_bold[red]Deleting WORKER horizontal pod autoscaler$reset_color"
kubectl delete -f worker-hpa.yml
echo -e "\n$fg_bold[red]Deleting WORKER service$reset_color"
kubectl delete -f worker-deployment.yml
echo -e "\n$fg_bold[red]Deleting Postgres$reset_color"
kubectl delete -f postgres-cluster-ip.yml -f postgres-deployment.yml

echo -e "\n$fg_bold[yellow]Delete Peristent Volume Claim? (y/n)$reset_color"
read ANSWER
if [[ $ANSWER = "y" ]]
then
  echo -e "\n$fg_bold[red]Deleting Peristent Volume Claim$reset_color"
  kubectl delete -f database-pvc.yml
fi

echo -e "\n$fg_bold[red]Deleting Redis$reset_color"
kubectl delete -f redis-cluster-ip.yml -f redis-deployment.yml
echo -e "\n$fg_bold[red]Deleting RabbitMQ$reset_color"
kubectl delete -f rabbitmq-cluster-ip.yml -f rabbitmq-deployment.yml
echo -e "\n$fg_bold[red]Deleting Secrets$reset_color"
kubectl delete -f secrets-vault.yml
echo -e "\n$fg_bold[red]Finished destroying cloud native system$reset_color\n"
