apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: taktzeit
  labels:
    app: database
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
  template:
    metadata:
      labels:
        component: database
        app: database
        version: 1.0.0
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-pvc
      containers:
        - name: postgres
          image: index.docker.io/postgres:16.3-alpine3.20
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              memory: 96Mi
              cpu: 750m
            requests:
              memory: 64Mi
              cpu: 75m
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -d
                - postgres
                - -U
                - postgres
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 2
            failureThreshold: 4
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -d
                - postgres
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 8
