apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip
  labels:
    app: database
    version: 1.0.0
spec:
  type: ClusterIP
  selector:
    component: database
  ports:
  - port: 5432
    name: tcp
    targetPort: 5432
