apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: messaging
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      component: messaging
  template:
    metadata:
      labels:
        component: messaging
        app: messaging
        version: 1.0.0
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9.13-alpine
        ports:
        - containerPort: 5672
        resources:
          limits:
            memory: "256Mi"
        env:
          - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
            value: -rabbit heartbeat 900
