apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: taktzeit
  labels:
    app: messaging
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      component: messaging
  template:
    metadata:
      labels:
        component: messaging
        app: messaging
        version: 1.0.0
    spec:
      containers:
        - name: rabbitmq
          image: index.docker.io/rabbitmq:3.13.3-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
          env:
            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: -rabbit heartbeat 900
          resources:
            limits:
              memory: 200Mi
              cpu: 1000m
            requests:
              memory: 144Mi
              cpu: 100m
