apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cluster-ip
  labels:
    app: messaging
    version: 1.0.0
spec:
  type: ClusterIP
  selector:
    component: messaging
  ports:
  - port: 5672
    targetPort: 5672
