apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip
  labels:
    app: cache
    version: 1.0.0
spec:
  type: ClusterIP
  selector:
    component: cache
  ports:
  - port: 6379
    targetPort: 6379
