FROM node:alpine
RUN apk update && \
    apk upgrade && \
    adduser --disabled-password --shell /bin/ash --ingroup users user
EXPOSE 5000
USER user
WORKDIR /home/user
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "dev"]
